// Generated by CoffeeScript 1.3.1
(function() {
  var resourceSet;

  resourceSet = new ecore.ResourceSet;

  resourceSet.load('http://127.0.0.1:5984/library/books', function(resource) {
    var item;
    console.log(resource);
    document.writeln(resource.content.name);
    return document.writeln((function() {
      var _i, _len, _ref, _results;
      _ref = resource.content.items;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        _results.push(item.title);
      }
      return _results;
    })());
  });

}).call(this);
